### ISSUE TITLE
When entering the name of a server that's not on the list pressing enter changes the name to the first fuzzy search result

### ISSUE THREAD

**Issue by phocks** [elk-zone/elk-native#12]
It should not do this imo.

**Comment by JonasKruckenberg** [comment]
This repo is not about tracking issues to the UI itself, that's part of the broader elk client (currently still private) if you want to submit feature proposals like this best get in touch with the core team on mastodon (or discord if you're a member there) and ask to get early access to the private repo so you can make suggestions there 👍🏻
