### ISSUE TITLE
Provide better build instruction

### ISSUE THREAD

**Issue by funkycode** [elk-zone/elk-native#14]
- Need to provide all dependencies: build and runtime
- Try to have sections of instructions per OS
- Have common issues and possible workaround for specific OS's

Details:
Need to provide more detailed instructions as I tried to build on ubuntu and debian (in docker) and they failed cause of the errors related to rust version and cargo install tauri-cli

Moreover I suggest to try to use [github workflow](https://github.com/tauri-apps/tauri-action) or dockerized build of AppImage to simplify the process

Will try to submit PR with updated instructions and possibly Dockerfile that will built app (I used arch linux as base image to do the build)

**Comment by JonasKruckenberg** [comment]
The README has this paragraph:
> First you will need to install Rust and other system dependencies required for developing a Tauri app, you can follow [this guide](https://tauri.app/v1/guides/getting-started/prerequisites).
Pointing you to the official Tauri docs that have exactly what you are looking for. If there's anything unclear with those docs we should edit and improve them instead IMO, as keeping separate docs in sync is a nightmare.

**Comment by funkycode** [comment]
I'll try to get there and send PR

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
