### ISSUE TITLE
Cannot back to Elk when not signed to Mastodon 

### ISSUE THREAD

**Issue by sxzz** [elk-zone/elk-native#15]
Cannot back to Elk when not signed to Mastodon. It will redirect to original Mastodon server.

For example, initially, I didn't sign in to `m.webtoo.ls`, and Elk will redirect me to webtools website and required my email and password. After signing in, it will redirect to `m.webtoo.ls` website instead of backing to Elk app.

**Comment by JonasKruckenberg** [comment]
I noticed the same thing (actually links have the same issue rn too I think) 
@danielroe can we open the mastodon login page within an iframe instead of the main context? or does that not work for oauth reasons?

**Comment by danielroe** [comment]
No, I don't think an iframe should work. And it really shouldn't do this. 🤔

Might need some investigation to see why this differs from the web app.

https://docs.joinmastodon.org/methods/oauth/

**Comment by JonasKruckenberg** [comment]
Hmm alright too bad, the broader issue here is that in the setting of a native app, the user doesn't have any navigation controls (so no back and forth buttons) to abort a mastodon login which is kinda unfortunate. If we could use an iframe (or indeed the users default browser maybe?) we could still retain that control over navigation.

**Comment by danielroe** [comment]
It might be possible to make the iframe thing work with a special route in elk 🤔

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
