### ISSUE TITLE
Native Mobile artifacts

### ISSUE THREAD

**Issue by ankushg** [elk-zone/elk-native#19]
I’m sure this is already on your radar, but wanted to make an issue to track so folks can subscribe for updates :)

**Comment by JonasKruckenberg** [comment]
Yes! This will not receive updates for a while though, just want to make that clear. Tauri mobile itself is in alpha right now and it's in alpha for a reason (e.g. elk on iOS works, but it doesn't Android yet) and there will be broader changes coming to it during the alpha phase. So I don't think putting out half-broken artifacts from a CI pipeline is worth it. As soon as Tauri mobile matures into beta and then later stable it's a different situation, but until then I think mobile will remain a largely experimental feature of this repo.

**Comment by marekvospel** [comment]
> Yes! This will not receive updates for a while though, just want to make that clear. Tauri mobile itself is in alpha right now and it's in alpha for a reason (e.g. elk on iOS works, but it doesn't Android yet) and there will be broader changes coming to it during the alpha phase. So I don't think putting out half-broken artifacts from a CI pipeline is worth it. As soon as Tauri mobile matures into beta and then later stable it's a different situation, but until then I think mobile will remain a largely experimental feature of this repo.

I was able to build the android application and install it using this repository. I had to make some minor adjustments and sign the apk using a self signed certificate for the installation to pass.
@JonasKruckenberg  If you want, I can make a PR into the mobile branch, but as you said, tauri mobile is in an experimental phase (eventhough I managed to install the app, I wasn't even able to sign in, as it kept crashing on the server select screen - maybe the auto suggestions caused it, but it's hard to tell), so it might be useless to try and get it running now.

**Comment by JonasKruckenberg** [comment]
> I was able to build the android application and install it using this repository. I had to make some minor adjustments and sign the apk using a self signed certificate for the installation to pass.

Interesting, did you test that the app works correctly too? bc I had trouble signing in on android, but at any rate I would really appreciate if you could list the adjustments you had to do/PR them 👍

**Comment by marekvospel** [comment]
> > I was able to build the android application and install it using this repository. I had to make some minor adjustments and sign the apk using a self signed certificate for the installation to pass.
> 
> Interesting, did you test that the app works correctly too? bc I had trouble signing in on android, but at any rate I would really appreciate if you could list the adjustments you had to do/PR them 👍

Ah, as I mentioned I wasn't able to sign in, as the app kept crashing on the select server screen / modal.
If you installed it you probably have gotten to the same point I did.

The tweaks were probably necessary due to my phone being older. (I installed it on a physical device)

I'll look over the tweaks and I'll update you in a PR or in this issue.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
