### ISSUE TITLE
Cannot Sign in when using packaged bundle

### ISSUE THREAD

**Issue by sxzz** [elk-zone/elk-native#2]
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/6481596/207036474-a55e731c-506b-4a15-83b1-b84931540866.png">

**Comment by alexzhang1030** [comment]
might because tauri cannot hosting a fullstack project

**Comment by sxzz** [comment]
Yeah, it's because we have to start the nodejs for running Elk, but Tauri doesn't include Node.js 🤔

**Comment by JonasKruckenberg** [comment]
@danielroe and me will figure this out on Wednesday, if anyone wants to join I guess we can make that possible too

**Comment by pro-sumer** [comment]
It's Thursday (in my timezone); did you figure it out?

(I don't see any commits or PR from yesterday - not trying to push; just curious)

**Comment by JonasKruckenberg** [comment]
This should be fixed now @danielroe did some fantastic fixes and even got signing in CI to work (check out the GH releases tab for a sneaky prerelease 😉)

**Comment by sxzz** [comment]
Maybe we could improve the filename of release files. Adding OS name like `darwin` or `macos` / `linux`
<img width="271" alt="image" src="https://user-images.githubusercontent.com/6481596/212316457-4f3e9a85-f20c-44c9-8995-5ffc171c0e7f.png">

**Comment by funkycode** [comment]
Now it allows to login but once I approve permissions for app I get blank screen with following:
![image](https://user-images.githubusercontent.com/594204/212530699-c7f63ae2-9455-4604-8bbd-8ccec446fa4d.png)

**Comment by danielroe** [comment]
IIRC the scheme in this case is `tauri:`

**Comment by JonasKruckenberg** [comment]
> Now it allows to login but once I approve permissions for app I get blank screen with following:
> 
> ![image](https://user-images.githubusercontent.com/594204/212530699-c7f63ae2-9455-4604-8bbd-8ccec446fa4d.png)
> 
> 

can you open a new issue for this and also provide the output of `tauri info` there?
