### ISSUE TITLE
Timeline does not update

### ISSUE THREAD

**Issue by pro-sumer** [elk-zone/elk-native#22]
Elk Native (macOS build) only shows the posts in the timeline at the time the App was started; no further posts appear.

Shouldn't Elk automatically load new posts? (Or at least offer a way to reload manually?)

**Comment by sync** [comment]
it reloads when you press on the elk :-)

**Comment by pro-sumer** [comment]
Thank you for informing me. I did not know...

Is Elk supposed to automatically reload the timeline as well?

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
