### ISSUE TITLE
Redirection to URL with a scheme that is not HTTP(S)

### ISSUE THREAD

**Issue by evilgeniuschronicles** [elk-zone/elk-native#27]
Installed Elk_0.1.0_linux_x86_64.deb on Pop!_OS with Eddy.

Authenticated against mastodon.lol, granted OAuth permission. Immediately after, I got the error in the title. I consistently see this - the very first time, after sign-out and sign-in when I no longer need to grant the permissions. Every time.

Once I get that, I can right click the body of the window and reload and from there it operates in parity with the Web UI. It is not obvious there is even a reload possible, I was just clicking at semi-random.

![Screenshot from 2023-01-17 11-04-53](https://user-images.githubusercontent.com/1059864/212952165-322795bb-4544-4bd4-ad16-b89ef2b31abe.png)

**Comment by lomby92** [comment]
The same for me.

Version:  Elk_0.2.1_linux_x86_64.deb

**Comment by kudos** [comment]
Still happening on 0.3.0

**Comment by kudos** [comment]
Might be a webkit-gtk problem https://github.com/samdroid-apps/something-for-reddit/issues/61#issuecomment-441433062

**Comment by kudos** [comment]
Another breadcrumb https://github.com/tauri-apps/wry/issues/127

**Comment by manan-gup** [comment]
Built from source on ArchLinux, ran the AppImage and I got the same message after auth. On doing right-click reload I get a flash of the left sidebar and then an empty black screen.

**Comment by librenyaa** [comment]
Currently on Linux Mint 21.1 with 0.4.0, issue is happening for me.

**Comment by tigexplorer** [comment]
Same here on ubuntu 22.4 with Appimage Elk Native v0.4.0

**Comment by manan-gup** [comment]
Tried again with the same result for Elk Native v0.4.0 on Ubuntu 22.04.2 LTS.
Got this message in the terminal when I tried to reload the "Redirection to URL..." page: `Asset 'api/hachyderm.io/oauth/tauri://localhost' not found; fallback to api/hachyderm.io/oauth/tauri://localhost.html`.

**Comment by GoodOldAbe** [comment]
This issue persists with Elk_0.4.0_linux_x86_64.deb on a Debian 12.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
