### ISSUE TITLE
Publish to Homebrew

### ISSUE THREAD

**Issue by sxzz** [elk-zone/elk-native#35]
I think we can publish to https://github.com/Homebrew/homebrew-cask

**Comment by piotrski** [comment]
It would be nice, but I would wait a bit until we polish a few major issues.

**Comment by shuuji3** [comment]
Ah, sorry, I submitted a PR to Homebrew/homebrew-cask just before reading the above comment: https://github.com/Homebrew/homebrew-cask/pull/139778. 🙏🏻 

I changed it to a draft PR now. Please let me know if you think you are ready to submit it. I can update the PR so that they can review and merge it.

**Comment by piotrski** [comment]
@shuuji3 do we have to update it in the homebrew repo every time we release a new version?

**Comment by sxzz** [comment]
@piotrski I think so. There are already 133k PR in the homebrew-cask repo. We have to make a PR when every release. 

Maybe we can have a release bot for homebrew in the future.

**Comment by JonasKruckenberg** [comment]
we can definitely have a workflow for submitting PRs, we need a similar thing to submit latest release links to the elk docs too though that's a different issue.

**Comment by shuuji3** [comment]
Yes, I think so too. But unless the current structure such as the package name convention and the release URL won't is changed, I think the only you need to change would be the version number and package hash: https://github.com/shuuji3/homebrew-cask/blob/add-elk/Casks/elk.rb#L4-L6

Also, Homebrew is providing the built-in subcommand called `brew bump-cask-pr` to upgrade and create a new PR with minimal effort. Maybe you can also use it in the automation.

**Comment by ShadowJonathan** [comment]
If i understand correctly, this can now be installed with `brew install --cask elk`, right?

**Comment by shuuji3** [comment]
@ShadowJonathan Yes, you're correct. I also confirmed that version v0.4.0 can be installed now with that command.

@JonasKruckenberg @sxzz Sorry, I was being waited for your approval but the original PR had been merged now. Do you think it's ok? Honestly, I think the current version of Elk native is enough stable and working well so we keep the published brew cask to provide users a way to test easily. You can also update the install documentation for Homebrew at any time you'd like maybe after additional iterations. What do you think?

**Comment by shuuji3** [comment]
After merging #96, marked the brew cask as deprecated by https://github.com/Homebrew/homebrew-cask/pull/171132
