### ISSUE TITLE
Copy link to post not working properly

### ISSUE THREAD

**Issue by Antimoon51** [elk-zone/elk-native#37]
if I want to share a post via link I can klick on copy link to this post (as seen in the screenshot) or on share this post and then copy link. However in both cases I get this link, that starts with `tauri.localhost` followed by the real link. as in: `https://tauri.localhost/<instance>/@<user>/<post-id>`
(sorry I don't know if it would be ok to post a link here..)

![grafik](https://user-images.githubusercontent.com/50957040/213379283-d1138847-83dd-4f7b-8a45-585fa2aa32aa.png)

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
