### ISSUE TITLE
Cloning of Submodule fails

### ISSUE THREAD

**Issue by jo** [elk-zone/elk-native#4]
Looks like submodule https://github.com/elk-zone/elk.git is not public, [but needed](https://github.com/elk-zone/elk-native/blob/main/README.md#local-setup).

:elephant: :elephant: :elephant: and thanks: Elk is quite pretty and fast! :elephant: :elephant: :elephant:

**Comment by patak-dev** [comment]
Hey @jo, Elk is in private alpha. But if you would like to get involved, you're welcome to help us get things ready for opening up. I sent you an invite to the Elk repo and you can join our discord at https://chat.elk.zone

**Comment by jo** [comment]
Thank you @patak-dev!

**Comment by patak-dev** [comment]
@pro-sumer invited 👍🏼 
We're going to open-source Elk in a few days, we should have added this note before. This repo was initially going to be closed too but it was opened because we needed the GitHub actions minutes.
