### ISSUE TITLE
macOS window dragging unavailable in wider viewports

### ISSUE THREAD

**Issue by tbeseda** [elk-zone/elk-native#43]
Elk.app v0.2.0
macOS 13.2

I noticed that window dragging is working in the latest release, but it seems finicky when the window is at certain breakpoints. I've attached a screencast video demonstrating.

https://user-images.githubusercontent.com/15697/213533347-4b37ea56-1a9a-4a1e-92cd-401295362c52.mp4

Thanks for the hard work here!

**Comment by piotrski** [comment]
It's related to #44 we need layout changes for a native app.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
