### ISSUE TITLE
Improve layout for larger screens

### ISSUE THREAD

**Issue by piotrski** [elk-zone/elk-native#44]
I am currently using the Elk app on a larger screen and I have noticed that there is empty space on the left and right. To improve the user experience, I suggest the following changes:

- The menu should be attached to the left side of the screen
- The timeline should fill the rest of the screen, and the right panel should appear on wider screens

One way to implement these changes would be to add a new variant to the unocss for native, which would only be included in Tauri builds.

**Comment by patak-dev** [comment]
The timeline is fixed at 600px because going above that currently destroys cards (for example social images are already quite blurry). So this requires quite a bit of work to have the cards maybe on the side? It is hard... other platforms also restrict to 600px max for the same reason I imagine.

**Comment by piotrski** [comment]
We could set the max width of the window, but then we won't show the right panel. This is not a big problem for now, but we should keep this in mind later when we add additional information on the right.
