### ISSUE TITLE
Publish on Flathub

### ISSUE THREAD

**Issue by gianni-rosato** [elk-zone/elk-native#46]
I see you have an AppImage available for download, but making the package available on Flathub will allow elk-native to be easily accessible to many via GUI package manager frontends like GNOME Software. Although this is not final software, you can publish it to Flathub’s beta repository. I think it’s worth a look, keep up the great work!

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
