### ISSUE TITLE
How to handle native-specific UI overrides? / Decreasing width required for sidebar.

### ISSUE THREAD

**Issue by sammarks** [elk-zone/elk-native#50]
For some context, I love the navigation sidebar at the left-side of the page.

![image](https://user-images.githubusercontent.com/424093/213750939-a9d854be-424e-4be9-8463-c39c84d5f925.png)

However, if I collapse the window below this width, the sidebar (rightly) turns into footer navigation since it detects it's probably being viewed on a mobile device.

That makes perfect sense for responsive web development, but in the case of a desktop app I'd like to decrease the content width a little bit more but still keep the sidebar there.

Additionally, I'm not sure there's a use case for the footer-based navigation on the desktop app, since on a desktop there is plenty of horizontal screen real-estate for all those navigation items. At the very least, if people like the footer-based navigation, it could be some sort of setting (I'm skeptical anyone would use it, but everyone has their own preferences).

---

With that said, I was going to put up a PR for this, but noticed there isn't any sort of system to override the styles inside the main Elk frontend. Shouldn't one be implemented?

Another potential feature that would make use of being able to modify the underlying JS: updating the sidebar to take advantage of MacOS' / Windows' transparency features (if you feel that fits the design / overall experience of Elk).

My initial idea is to have some sort of patch system where the native app can run patches on the frontend code. That's probably ripe for bugs, especially as things change in the main codebase, so hopefully there's a better way!

Anyway, just thought it might be worth starting a conversation around this. Love the app so far!

**Comment by JonasKruckenberg** [comment]
With elk-zone/elk#1359 we now have a system for platform specific styles/elk-native specific styles. 

To fix this issue immediately, I set a `minWidth` for the window, which makes sense generally IMO (no app design looks good if your app is 100px wide 😅) but with elk-native specific styles we can decrease the breakpoint for the bottom navigation and then update the minWidth accordingly. If you care deeply about the minWidth being smaller than the current 640px open an issue over at the main repo! Thanks for bringing this up!
