### ISSUE TITLE
MacOS Native - not seeing load new posts counter

### ISSUE THREAD

**Issue by DanAncona** [elk-zone/elk-native#52]
The "load new posts" counter isn't showing up for me in the most recent build, Elk v0.6.1, MacOS Monterey 12.5. Sorry, I may be forgetting the exact wording, but it's the thing at the top of the stack of posts that you can click to load new posts.

BTW this is a very nice feature, and another thing I like more than how certain other microblogging service native apps work.

Here's the log - looks truncated, let me know if there's something else you need here.
[Elk.log](https://github.com/elk-zone/elk-native/files/10469953/Elk.log)

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
