### ISSUE TITLE
[UI] Strange top bar

### ISSUE THREAD

**Issue by bigshans** [elk-zone/elk-native#64]
Well, I met this problem only in the native app. When I maximize the window, the top bar of notifications will extend to the far right. It looks strange. Can you make it more natural?

![图片](https://user-images.githubusercontent.com/26884666/215272900-12e12357-a15e-4e0f-a3f9-41786f70726a.png)

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
