### ISSUE TITLE
Use `extends` instead of git submodule setup

### ISSUE THREAD

**Issue by danielroe** [elk-zone/elk-native#65]
Currently we use git submodules to check out https://github.com/elk-zone/elk. This means our options for customising elk for native build are more limited and often have to happen upstream, which can hold back development of elk-native.

Instead, I propose we use the [Nuxt extends/layers feature](https://nuxt.com/docs/getting-started/layers#layers) ([issue tracker](https://github.com/nuxt/framework/issues/3222)) to build on top of existing elk app.

This will allow us to move the tauri module that currently exists upstream into this rep and address issues like https://github.com/elk-zone/elk/pull/1492 more easily.

**Comment by jbolda** [comment]
Does that mean that this repo would consume elk as a npm (registry) dependency? We would have a minimal Nuxt setup and extend the elk-zone/elk dependency.

Or are you thinking monorepo with shared code and layers to customize the remaining bits that are specifically web only vs app only?

Either way, I would personally prefer moving away from submodules.
