### ISSUE TITLE
Missing Android Release

### ISSUE THREAD

**Issue by stijnhommes** [elk-zone/elk-native#70]
You've got releases for Linux, Ubuntu, Windows, and MacOS. 
Where are the native releases for Android and iOS?
That's a pretty big gap for people who want to use Elk natively on mobile.

**Comment by Moshyfawn** [comment]
I don't think mobile bins are on the table ATM. [Tauri](https://tauri.app/), the framework used to bring the web client to desktop [just had their alpha release](https://tauri.app/blog/2022/12/09/tauri-mobile-alpha/#docusaurus_skipToContent_fallback) with the mobile support.

**Comment by Moshyfawn** [comment]
Related #19

**Comment by stijnhommes** [comment]
So if you want to use Elk on mobile, your only choice is to settle for a "web app" instead of a native app because everyone is focussed on Tauri, rather than native mobile support.

I'll try to stay informed about the progress of Elk native, but right now, it appears I have to look for an alternative with solid native mobile support instead.

**Comment by JonasKruckenberg** [comment]
As stated in the other linked issue mobile support would be neat and is definitely "on the roadmap" for elk-native if you will. But given that Tauri mobile itself is still experimental and APIs needed to bring elk to Android aren't supported yet we're focusing on the desktop experience right now. Subscribe to that other issue if you want to receive updates 👍
