### ISSUE TITLE
Blank screen and unresponsive after logging-in on v0.4.0 - MacOS Ventura

### ISSUE THREAD

**Issue by wilberfan** [elk-zone/elk-native#74]
I get a display until I try to login to my instance.  Following the authorization screen, the window is completely white (empty), and I cannot click-and-drag the window anywhere.  MacOS Ventura 13.2.1, M1.

**Comment by tomayac** [comment]
Same here. It flashes the navigation bar on the left for a split-second, but then the screen stays white (in light mode) or black (in dark mode).

**Comment by wub-fur** [comment]
Having the same issue under Monterey 12.6.3 on a Mac Studio. Just trying elk-native for the first time (I use the elk web app all the time in Firefox on this Mac and Safari on my iPad).

**Comment by noahtren** [comment]
Also getting this problem on Big Sur 11.6

**Comment by pupbrained** [comment]
Same problem here on Ventura 13.2.1, M2 Air

**Comment by joshsharp** [comment]
Same issue (on Windows 10). Doesn't seem OS-specific.

**Comment by mxcop** [comment]
Same problem also happening on Windows 11.

**Comment by colindean** [comment]
Same, Windows 10 logging into Mastodon.social.

**Comment by lucacorbucci** [comment]
Same here, macos Ventura 13.2

**Comment by nagyfrantisek** [comment]
Dirty workaround:
- Delete 0.4.0
- Install 0.3.0
- Open 0.3.0 and sign in
- Close 0.3.0
- Open 0.3.0 and press update to 0.4.0

**Comment by rcjcarr** [comment]
Same here, blank screen (white), no login credentials asked at any point. Changed directory permissions and followed all self-hosted steps. Rebooted to no avail. Running docker in a proxmox LXC container, privileged.

**Comment by OfficialCRUGG** [comment]
Issue still persists on Sonoma. Can use the app fine as guest, but as soon as I try to log in it's a blank screen.

![image](https://github.com/elk-zone/elk-native/assets/25248999/609fed58-ca2d-456d-be29-1df3645ab3a6)

**Comment by tomayac** [comment]
CC: @nothingismagick, whom I just mentioned this issue to.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is [no longer maintained](https://github.com/elk-zone/elk-native/pull/96/), much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️

**Comment by colindean** [comment]
@JonasKruckenberg thanks for letting us know. Proactive notification that a project is no longer maintained is rare and I really appreciate that notification.
