### ISSUE TITLE
Miscounting characters in post

### ISSUE THREAD

**Issue by jbwharris** [elk-zone/elk-native#8]
I just had an instance where my post was exactly 500 characters and pushed publish and nothing happened. I copied and pasted my response into another app and it said I was 4 characters over 500. I edited the post to remove 4 characters and it posted fine.

**Comment by felix9** [comment]
I ran into this problem when replying to a CW'ed post. It looks to me like elk is not including the CW in the character count.

(can easily verify this by drafting a new post with a CW. the CW doesn't affect the count in elk, but it does on mastodon web)

**Comment by sxzz** [comment]
Yeah we had the issue on the private repo already https://github.com/elk-zone/elk/issues/639

We'll investigate it.

**Comment by TodePond** [comment]
I think this should be fixed on https://main.elk.zone now! https://github.com/elk-zone/elk/issues/639#issuecomment-1374434162
