### ISSUE TITLE
After login and authorization click for elk in mastodon it redirects to a not https site iE http

### ISSUE THREAD

**Issue by mitvitaminen** [elk-zone/elk-native#82]
After login and authorization click for elk in mastodon it redirects to a not https site iE http failing to authorize and therfore the complete login fails. This is with ravenation.club server .

**Comment by GoodOldAbe** [comment]
Hello,

I believe I have the problem. When I provide my credentials and authorize the access from the application to my account, I end up on a blank screen with only the text : "Redirection to URL with a scheme that is not HTTP(S)".

I use the desktop application, on a x86_64 architecture with a Debian 12.

**Comment by mickeymarse** [comment]
That's not the only server it happens with. I've experienced the same issue with mine.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️

**Comment by ckiyme** [comment]
> Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed. Please use the actively maintained elk PWA instead.
> 
> Thanks so much for your support and understanding so far! ❤️

Thank you all for the work so far!
Will you be willing to onboard new maintainers in the future? Is there a process for that?
