### ISSUE TITLE
Provide builds for arm on windows (WOA)

### ISSUE THREAD

**Issue by intzaaa** [elk-zone/elk-native#83]
this is very simple:

```
rustup target add aarch64-pc-windows-msvc
tauri build --target aarch64-pc-windows-msvc --bundles nsis
```

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
