### ISSUE TITLE
Color shifted to orange when viewing users profile's default "posts" section

### ISSUE THREAD

**Issue by rilysh** [elk-zone/elk-native#85]
When viewing a user's profile, I saw a light yellow color on the followers list count side. Is that intended behavior? However, clicking on the "post with replies" or "media" section the color goes back to normal (gets shifted to white color). 

Here's the recording video

[simplescreenrecorder-2023-08-01_13.31.14.webm](https://github.com/elk-zone/elk-native/assets/71683721/7ef880a0-b805-41af-a1af-7c05d14ddae1)

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
