### ISSUE TITLE
"Cannot connect to server" when attempting to sign in

### ISSUE THREAD

**Issue by solonovamax** [elk-zone/elk-native#89]
Hi,

I am getting the "Cannot connect to server" error message when attempting to sign in:
![image](https://github.com/elk-zone/elk-native/assets/46940694/de46456a-c0a8-4ad8-8233-c543d2e140b0)![image](https://github.com/elk-zone/elk-native/assets/46940694/17d5e26a-4be7-4ba0-95e5-8259b4b81575)![image](https://github.com/elk-zone/elk-native/assets/46940694/5911de26-b1f8-4a42-8ad5-a99c5a52d30d)

Note: my instance is tech.lgbt, however I have also tested the mastodon.social and m.webtoo.ls servers.

I am using a version compiled from master. When running a release that has been compiled with `cargo tauri build --debug` (note: I can reproduce on a debug build as well as a non-debug build, installed from the AUR), the following log message is produced when attempting pressing the "Sign in" button:
```
[2023-12-05][18:26:18][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
```

The full logs are:
```
[2023-12-05][18:26:00][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][WARN] @nuxtjs/i18n Could not find en-US locale code in localeMessages
VM 0x7feb1e400000 on pid 22127 received NeedDebuggerBreak trap
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
[2023-12-05][18:26:18][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
[2023-12-05][18:26:33][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
[2023-12-05][18:26:43][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
[2023-12-05][18:26:45][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
[2023-12-05][18:27:22][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
[2023-12-05][18:28:33][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
[2023-12-05][18:29:16][ha@tauri://localhost/_nuxt/entry.00b77760.js:18:20962][ERROR] [h3]
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
Couldn't get key from code: SuperLeft
```

Additionally, there is nothing in the browser console of interest.
Here is the full contents of the browser console:
```
[Error] Origin tauri://localhost is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] Fetch API cannot load https://m.webtoo.ls/nodeinfo/2.0 due to access control checks.
[Error] Failed to load resource: Origin tauri://localhost is not allowed by Access-Control-Allow-Origin. Status code: 200 (2.0, line 0)
```

Looking at the network requests, it does not seem to be making any requests, other than loading 2 inline svgs.

After messing around trying to get source maps to build so I can figure out where that error is from (I couldn't get it to work), I eventually managed to do smth that started showing the following console logs:
```
[Error] Refused to connect to tauri://localhost/api/tech.lgbt/login because it does not appear in the connect-src directive of the Content Security Policy.
```

so, my best guess, is that for some reason it doesn't want to connect to the internal server ? Unsure, though.
It also produced the following logs in the browser console:
```
[Warning] @nuxtjs/i18n Could not find en-US locale code in localeMessages (entry.864cc6c3.js, line 39)
[Error] Origin tauri://localhost is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] Fetch API cannot load https://m.webtoo.ls/nodeinfo/2.0 due to access control checks.
[Error] Failed to load resource: Origin tauri://localhost is not allowed by Access-Control-Allow-Origin. Status code: 200 (2.0, line 0)
[Error] Refused to connect to tauri://localhost/api/list-servers because it does not appear in the connect-src directive of the Content Security Policy. (x2)
[Error] FetchError: Load failed (/api/list-servers)
	ow (entry.864cc6c3.js:1:14337)
	zo (entry.864cc6c3.js:1:14290)
	(anonymous function) (entry.864cc6c3.js:1:13948)
[Error] Refused to connect to tauri://localhost/api/tech.lgbt/login because it does not appear in the connect-src directive of the Content Security Policy.
```

**Comment by jpmcb** [comment]
👀 Also getting this on `fosstodon.org` and can't log in

![Screenshot 2023-12-08 at 5 00 09 PM](https://github.com/elk-zone/elk-native/assets/23109390/2d6fe8e2-95de-43bc-854b-742b03c81dd5)

**Comment by lo0sr** [comment]
I am currently having the same issue when trying to connect to infosec.exchange

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
