### ISSUE TITLE
MacOS: not getting passed Nuxt screen

### ISSUE THREAD

**Issue by jpmcb** [elk-zone/elk-native#91]
Hi all - thanks so much for this awesome client.

Trying to get this to run using `cargo tauri dev`, it's not loading anything - just stuck on the Nuxt slash screen:

![Screenshot 2023-12-08 at 4 35 36 PM](https://github.com/elk-zone/elk-native/assets/23109390/308f6154-aeda-4cfb-ae2a-896083491314)

Any tips? This is off of the head of main: 73fd12c74fbe89a33c7e9d791a02a848a3a7957c.

Some system stats:
```
Software:

    System Software Overview:

      System Version: macOS 13.3 (22E252)
      Kernel Version: Darwin 22.4.0
```

```
❯ cargo --version
cargo 1.73.0 (9c4383fb5 2023-08-26)
```

Any help would be a big thanks - would love to help here as much as possible!! ❤️

**Comment by jpmcb** [comment]
Building the app works with `cargo tauri build`

![Screenshot 2023-12-08 at 4 52 00 PM](https://github.com/elk-zone/elk-native/assets/23109390/e0ce1fe7-0e9f-430a-bf9a-c38e7e41fac7)

Also tried updating to the newest rust / cargo without any new results on the dev build.

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
