### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Jak2k** [elk-zone/elk-native#94]
```
 Finished release [optimized] target(s) in 1m 40s
    Bundling elk_0.4.0_amd64.deb (/home/jak2k/software/elk-native/target/release/bundle/deb/elk_0.4.0_amd64.deb)
    Bundling elk_0.4.0_amd64.AppImage (/home/jak2k/software/elk-native/target/release/bundle/appimage/elk_0.4.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh
```

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
