### ISSUE TITLE
Graphics issues on wayland

### ISSUE THREAD

**Issue by Jak2k** [elk-zone/elk-native#95]
Text is blurry and window flickers on Wayland (+hyprland).

![Fri Mar 15 10:17:55 PM CET 2024](https://github.com/elk-zone/elk-native/assets/76660118/803aa4fb-f00a-42f0-bdd2-71eac14a3590)

**Comment by JonasKruckenberg** [comment]
Hey! Just letting you know that elk-native is no longer maintained, much of the team has moved on or is busy with other projects (there's only so much time in a day 😅), so this issue will likely not be fixed.
Please use the actively maintained elk PWA instead.

Thanks so much for your support and understanding so far! ❤️
